export const FETCHED_DATA = "FETCHED_DATA";
export const ADD_NEW_DOMAIN = "ADD_NEW_DOMAIN";
export const DELETE_DOMAIN = "DELETE_DOMAIN";
export const ADD_PASSWORD = "ADD_PASSWORD";

export const IS_RESOLVED = "IS_RESOLVED";
export const INCLUDE_RESOLVED = "INCLUDE_RESOLVED";
export const HANDLE_TOAST = "HANDLE_TOAST";
export const HANDLE_DELETE_MODAL = "HANDLE_DELETE_MODAL";
export const HANDLE_RESOLVED_MODAL = "HANDLE_RESOLVED_MODAL";
